// This file will be auto-generated by `supabase gen types`
// to provide TypeScript definitions for your database schema.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]