server:
  http_listen_port: 9080
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: docker-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
    pipeline_stages:
      - json:
          expressions:
            log: log
      - regex:
          expression: '^(?P<ts>.*)$'
          source: log
      - json:
          source: log
          expressions:
            level: level
            service: service
            env: env
            run_id: run_id
            job_id: job_id
            domain: domain
            url: url
            proxy_id: proxy_id
            trace_id: trace_id
            span_id: span_id
            message: message
      - labels:
          level:
          service:
          env:
          domain:
          run_id:
          job_id:
          trace_id:
          span_id:
      - timestamp:
          source: ts
          format: RFC3339
      - output:
          source: message