route:
  group_by: ["alertname", "domain"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 2h
  receiver: slack-notify
  routes:
    - matchers:
        - severity="critical"
      receiver: slack-critical
receivers:
  - name: slack-notify
    slack_configs:
      - api_url: "https://hooks.slack.com/services/XXX/YYY/ZZZ"
        channel: "#scraping-alerts"
        send_resolved: true
  - name: slack-critical
    slack_configs:
      - api_url: "https://hooks.slack.com/services/XXX/YYY/ZZZ"
        channel: "#scraping-pager"
        send_resolved: true
inhibit_rules:
  - source_matchers: [ "severity=critical" ]
    target_matchers: [ "severity=warning" ]
    equal: ["alertname","domain"]