version: "3.9"
services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=15d
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules:/etc/prometheus/rules:ro
      - prom_data:/prometheus
    ports: [ "9090:9090" ]
    networks: [ obsv ]

  grafana:
    image: grafana/grafana:11.0.0
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    ports: [ "3000:3000" ]
    depends_on: [ prometheus, loki, tempo ]
    networks: [ obsv ]

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: [ "-config.file=/etc/loki/config.yml" ]
    volumes:
      - ./loki/loki-config.yml:/etc/loki/config.yml:ro
      - loki_data:/loki
    ports: [ "3100:3100" ]
    networks: [ obsv ]

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    command: [ "-config.file=/etc/promtail/config.yml" ]
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks: [ obsv ]

  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    command: [ "-config.file=/etc/tempo/tempo.yml" ]
    volumes:
      - ./tempo/tempo.yml:/etc/tempo/tempo.yml:ro
      - tempo_data:/tmp/tempo
    ports: [ "3200:3200" ]
    networks: [ obsv ]

  otel-collector:
    image: otel/opentelemetry-collector:0.99.0
    container_name: otel-collector
    command: [ "--config=/etc/otelcol/config.yml" ]
    volumes:
      - ./otel-collector/config.yml:/etc/otelcol/config.yml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    networks: [ obsv ]
    depends_on: [ tempo ]

volumes:
  prom_data: {}
  grafana_data: {}
  loki_data: {}
  tempo_data: {}

networks:
  obsv: {}