// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvinyqtypnyagcpqutog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2aW55cXR5cG55YWdjcHF1dG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDU5MDksImV4cCI6MjA3MDA4MTkwOX0.6eDShz2J6uSf1_ECxDlo2ZqcCAIEVp3cxrmw7JdlOVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});