version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_net

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app_net

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: python scripts/start_scheduler.py
    env_file:
      - .env
    depends_on:
      - api
      - redis
    networks:
      - app_net

networks:
  app_net:
    driver: bridge