version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_net

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app_net

  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python scripts/start_scheduler.py
    env_file:
      - .env
    depends_on:
      - api
      - redis
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app_net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      - app_net

networks:
  app_net:
    driver: bridge