# Anti-bot policies and strategies
# Note: This is for ethical, policy-driven behavior, not for bypassing protections.

default_delay_strategy:
  type: adaptive
  min_delay_seconds: 2
  max_delay_seconds: 10
  backoff_factor: 2
  max_retries: 3

header_strategy:
  user_agent_pool:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
    - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36"
  accept_language: "en-US,en;q=0.9"

session_management:
  rotate_session_after_requests: 100
  clear_cookies_on_rotate: true