# Main application configuration
app_name: "Ethical Crawler & Data Platform"
version: "0.1.0"
environment: "development" # Overridden by env files

database:
  provider: "supabase"
  pool_size: 10

api:
  host: "0.0.0.0"
  port: 8000