# 🦉 Sparkling-Owl-Spin - Enhetlig Konfiguration
# ====================================================
# Huvudkonfigurationsfil för hela pyramid-arkitekturen

# System Information
system:
  name: "Sparkling-Owl-Spin"
  version: "1.0.0"
  architecture: "Pyramid"
  status: "Production Ready"

# Core Configuration
core:
  orchestrator:
    enabled: true
    host: "0.0.0.0"
    port: 8000
    workers: 4
    
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "logs/sparkling_owl_spin.log"
    
  security:
    enable_cors: true
    allowed_origins: ["*"]
    rate_limiting: true
    max_requests_per_minute: 100

# Database Configuration
database:
  primary:
    type: "postgresql"
    host: "localhost"
    port: 5432
    database: "sparkling_owl_spin"
    username: "sparkling_user"
    password: "${DATABASE_PASSWORD}"
    
  cache:
    type: "redis"
    host: "localhost"
    port: 6379
    database: 0

# Engine Configuration
engines:
  bypass:
    cloudflare:
      enabled: true
      timeout: 30
      retry_attempts: 3
      
    captcha:
      enabled: true
      services: ["2captcha", "nopecha", "anticaptcha"]
      timeout: 60
      
    waf:
      enabled: true
      detection_timeout: 10
      bypass_methods: ["header_manipulation", "encoding_bypass"]
      
  scraping:
    default_engine: "requests"
    fallback_engines: ["selenium", "playwright"]
    timeout: 30
    max_retries: 3
    
    requests:
      user_agents_pool: 50
      connection_pool_size: 100
      
    selenium:
      browser: "chrome"
      headless: true
      stealth_mode: true
      
    playwright:
      browser: "chromium"
      headless: true
      stealth: true

# Swedish Integrations
integrations:
  swedish:
    blocket:
      enabled: true
      rate_limit: 10
      cache_ttl: 3600
      
    bolagsverket:
      enabled: true
      api_key: "${BOLAGSVERKET_API_KEY}"
      rate_limit: 5
      
    biluppgifter:
      enabled: true
      rate_limit: 20
      cache_ttl: 7200

# Proxy Configuration
proxy:
  enabled: true
  rotation_strategy: "round_robin"
  health_check_interval: 300
  
  sources:
    - name: "premium_pool"
      enabled: true
      url: "${PREMIUM_PROXY_URL}"
      auth: "${PREMIUM_PROXY_AUTH}"
      
    - name: "free_pool"
      enabled: true
      sources: ["proxy-list", "free-proxy-list"]
      
# Ethical Settings
ethics:
  respect_robots_txt: true
  default_delay: 1.0
  max_concurrent_requests: 5
  user_agent: "Sparkling-Owl-Spin/1.0 (Ethical Web Scraper)"
  
# Monitoring
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_endpoint: "/health"
  
  alerts:
    error_rate_threshold: 10
    response_time_threshold: 5000
    
# Export Configuration
export:
  formats: ["json", "csv", "xlsx"]
  compression: true
  batch_size: 1000
  
  destinations:
    local:
      enabled: true
      path: "exports/"
      
    database:
      enabled: true
      table_prefix: "scraped_"
      
    cloud:
      enabled: false
      provider: "aws_s3"
      bucket: "${AWS_S3_BUCKET}"
