# Logging configuration
version: 1
disable_existing_loggers: false

formatters:
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  json_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: app.log
    maxBytes: 10485760 # 10MB
    backupCount: 5

loggers:
  "ECaDP":
    level: DEBUG
    handlers: [console, json_file]
    propagate: no

root:
  level: INFO
  handlers: [console]