groups:
- name: ECaDP_Alerts
  rules:
  - alert: HighApiErrorRate
    expr: sum(rate(http_requests_total{code=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "High API Error Rate"
      description: "More than 5% of API requests are failing with 5xx errors."

  - alert: ThroughputDrop
    expr: sum(rate(http_requests_total[10m])) < (sum(rate(http_requests_total[1h] offset 1h))) * 0.5
    for: 15m
    labels:
      severity: warning
    annotations:
      summary: "API Throughput Drop"
      description: "API request throughput has dropped by more than 50% compared to one hour ago."

  - alert: LowDataQualityScore
    expr: avg(data_quality_score) < 0.8
    for: 30m
    labels:
      severity: warning
    annotations:
      summary: "Low Data Quality Score"
      description: "The average data quality score has been below 80% for the last 30 minutes."