version: "3.9"

services:
  # Statisk lista med paginering - för crawler/scraper-tester
  synthetic-static:
    build: 
      context: .
      dockerfile: synthetics/static_list/Dockerfile
    container_name: synthetic-static
    ports: 
      - "8081:8081"
    environment:
      - PORT=8081
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Infinite scroll-test för browser-mode
  synthetic-scroll:
    build:
      context: .
      dockerfile: synthetics/infinite_scroll/Dockerfile
    container_name: synthetic-scroll
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8082/"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Formulärflöde-test för interaktiva funktioner
  synthetic-form:
    build:
      context: .
      dockerfile: synthetics/form_flow/Dockerfile
    container_name: synthetic-form
    ports:
      - "8083:8083"
    environment:
      - PORT=8083
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8083/"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    name: synthetic-test-network