apiVersion: v1
kind: Namespace
metadata:
  name: ops
  labels:
    name: ops
    environment: production
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ops-limit-range
  namespace: ops
spec:
  limits:
  - default:
      memory: "512Mi"
      cpu: "250m"
    defaultRequest:
      memory: "128Mi"
      cpu: "50m"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ops-quota
  namespace: ops
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    pods: "10"
    services: "5"
