apiVersion: v1
kind: Namespace
metadata:
  name: scraping
  labels:
    name: scraping
    environment: production
---
apiVersion: v1
kind: LimitRange
metadata:
  name: scraping-limit-range
  namespace: scraping
spec:
  limits:
  - default:
      memory: "1Gi"
      cpu: "500m"
    defaultRequest:
      memory: "256Mi"
      cpu: "100m"
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: scraping-quota
  namespace: scraping
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
