name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-type:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Run linters and type checking
      run: |
        ruff check .
        black --check .
        mypy src

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint-and-type
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Run unit tests
      run: pytest -m unit

  integration-tests:
    runs-on: ubuntu-latest
    needs: lint-and-type
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Start synthetic services
      run: docker-compose -f docker/docker-compose.synthetic.yml up -d
    - name: Run integration tests
      run: pytest -m integration
    - name: Stop synthetic services
      if: always()
      run: docker-compose -f docker/docker-compose.synthetic.yml down

  e2e-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: integration-tests
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
    - name: Install Playwright browsers
      run: playwright install --with-deps
    - name: Start synthetic services
      run: docker-compose -f docker/docker-compose.synthetic.yml up -d
    - name: Run E2E tests
      run: pytest -m e2e
    - name: Stop synthetic services
      if: always()
      run: docker-compose -f docker/docker-compose.synthetic.yml down