name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements_dev.txt
      - name: Unit tests
        run: pytest -m unit --maxfail=1 --disable-warnings -q

  integration:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements_dev.txt
      - name: Start synthetic sites
        run: docker compose -f docker/docker-compose.synthetic.yml up -d
      - name: Integration tests
        run: pytest -m "integration and not browser" -q

  e2e:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements_dev.txt
      - name: Start synthetic sites
        run: docker compose -f docker/docker-compose.synthetic.yml up -d
      - name: E2E tests
        run: pytest -m "e2e and not browser" -q