name: Windows tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: windows-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  windows:
    name: Windows Py${{ matrix.PYTHON_VERSION }}
    runs-on: windows-latest
    env:
      CI: True
      QTCONSOLE_TESTING: True
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'windows'
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.9', '3.10', '3.11']
    timeout-minutes: 15
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install Conda and install package dependencies
        uses: conda-incubator/setup-miniconda@v3
        with:
           activate-environment: test
           auto-update-conda: false
           auto-activate-base: false
           miniforge-version: latest
           mamba-version: "*"
           channels: conda-forge
           channel-priority: true
           python-version: ${{ matrix.PYTHON_VERSION }}
           environment-file: requirements/environment.yml # Need to set up dependencies in the same step due to https://github.com/conda-incubator/setup-miniconda/issues/371
      - name: Show environment information
        shell: bash -el {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -el {0}
        run: pytest -vv --color=yes --cov=qtconsole qtconsole
